export const ERROR_CODES = {
  LICENSE_VALID: "LICENSE_VALID",
  LICENSE_INVALID: "LICENSE_INVALID",
  LICENSE_DISABLED: "LICENSE_DISABLED",
  LICENSE_EXPIRED: "LICENSE_EXPIRED",
  LICENSE_REFUNDED: "LICENSE_REFUNDED",
  LICENSE_ACTIVATION_LIMIT_REACHED: "LICENSE_ACTIVATION_LIMIT_REACHED",
  LICENSE_MACHINE_ALREADY_ACTIVE: "LICENSE_MACHINE_ALREADY_ACTIVE",
  LICENSE_MACHINE_NOT_ACTIVE: "LICENSE_MACHINE_NOT_ACTIVE",
  LICENSE_SERVER_UNAVAILABLE: "LICENSE_SERVER_UNAVAILABLE",
  LICENSE_SIGNATURE_INVALID: "LICENSE_SIGNATURE_INVALID",
  LICENSE_TOKEN_EXPIRED: "LICENSE_TOKEN_EXPIRED",
  LICENSE_GRACE_ACTIVE: "LICENSE_GRACE_ACTIVE",
  LICENSE_GRACE_EXPIRED: "LICENSE_GRACE_EXPIRED",
  LICENSE_PRODUCT_MISMATCH: "LICENSE_PRODUCT_MISMATCH",
  LICENSE_VERSION_BLOCKED: "LICENSE_VERSION_BLOCKED",
  CONFIG_MISSING: "CONFIG_MISSING",
  DOWNLOAD_NOT_CONFIGURED: "DOWNLOAD_NOT_CONFIGURED",
  RELEASE_NOT_FOUND: "RELEASE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",
};

export function publicMessage(code) {
  const messages = {
    [ERROR_CODES.LICENSE_VALID]: "License active",
    [ERROR_CODES.LICENSE_INVALID]: "License invalid",
    [ERROR_CODES.LICENSE_DISABLED]: "License disabled",
    [ERROR_CODES.LICENSE_EXPIRED]: "License expired",
    [ERROR_CODES.LICENSE_REFUNDED]: "License refunded",
    [ERROR_CODES.LICENSE_ACTIVATION_LIMIT_REACHED]: "Activation limit reached",
    [ERROR_CODES.LICENSE_MACHINE_ALREADY_ACTIVE]: "This computer is already active",
    [ERROR_CODES.LICENSE_MACHINE_NOT_ACTIVE]: "This computer is not active",
    [ERROR_CODES.LICENSE_SERVER_UNAVAILABLE]: "License server unavailable",
    [ERROR_CODES.LICENSE_SIGNATURE_INVALID]: "License token signature invalid",
    [ERROR_CODES.LICENSE_TOKEN_EXPIRED]: "License token expired",
    [ERROR_CODES.LICENSE_GRACE_ACTIVE]: "Offline grace is active",
    [ERROR_CODES.LICENSE_GRACE_EXPIRED]: "Offline grace expired",
    [ERROR_CODES.LICENSE_PRODUCT_MISMATCH]: "License is for another product",
    [ERROR_CODES.LICENSE_VERSION_BLOCKED]: "This app version is blocked",
    [ERROR_CODES.CONFIG_MISSING]: "Server configuration is incomplete",
    [ERROR_CODES.DOWNLOAD_NOT_CONFIGURED]: "Protected downloads are not configured",
    [ERROR_CODES.RELEASE_NOT_FOUND]: "Release not found",
    [ERROR_CODES.VALIDATION_ERROR]: "Request validation failed",
    [ERROR_CODES.WEBHOOK_SIGNATURE_INVALID]: "Webhook signature invalid",
  };

  return messages[code] || "Request failed";
}
